[package]
name = "ssp"
description = "SSP handler for"
version = "0.1.0"
edition = "2021"

[dependencies]
ssp_schema = { path ="../ssp_schema"}
tempfile = {version ="3.12"}
zip = {version ="2.2.0", default_features = false, features=["bzip2"] }
log = {version ="0.4"}