[package]
name = "ssp_schema"
version = "0.1.0"
description = "XML schema support for SSP 1.0.1"
edition = "2021"

[dependencies]
yaserde = { version = "0.10.1" }
yaserde_derive = { version = "0.10.1" }
log = {version ="0.4"}
xml-rs = "0.8.3"

