[package]
name = "ssp_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ssp = { path ="../ssp" }
ssp_schema = { path ="../ssp_schema"}
log = {version ="0.4"}
env_logger = {version = "0.11.5"}

petgraph = {version = "0.6.5"}